VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsLeaveRecord"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public LeaveType As String
Public StartDT As Date
Public EndDT As Date
Public Reason As String
Public Status As String
Public RawStart As String
Public RawEnd As String
